version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: ./services/op/builder-client/Dockerfile
    container_name: 'builder'
    environment:
      PRIVATE_KEY_DEPLOYER: ${PRIVATE_KEY_ADMIN}
      PRIVATE_KEY_SEQUENCER: ${PRIVATE_KEY_SEQUENCER}
      PRIVATE_KEY: ${PRIVATE_KEY_ADMIN}
      ADMIN_ADDRESS: ${ADMIN_ADDRESS}
      SEQUENCER_ADDRESS: ${SEQUENCER_ADDRESS}
      BATCHER_ADDRESS: ${BATCHER_ADDRESS}
      PROPOSER_ADDRESS: ${PROPOSER_ADDRESS}
      L1_RPC: ${L1_RPC}
      L1_CHAIN_ID: ${L1_CHAIN_ID}
      ETH_RPC_URL: ${L1_RPC}
      DEPLOYMENT_CONTEXT: ${DEPLOYMENT_CONTEXT}
      L2_BLOCKTIME: ${L2_BLOCKTIME}
      L1_BLOCKTIME: ${L1_BLOCKTIME}
      L2_CHAIN_ID: ${L2_CHAIN_ID}
    volumes:
      - opstack-volume:/opstack/
      - ./tools/templates:/opstack-temp/tools/templates
      - ./tools/bash_scripts:/opstack-temp/tools/bash_scripts
      - ./assets:/assets
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:59100"
        syslog-format: "rfc3164"
        tag: "builderlogs"
    command: "sh /opstack-temp/tools/bash_scripts/init_client.sh"

  opgeth:
    image: shards-builder
    container_name: 'opgeth'
    environment:
      GETH_BOOTNODES: ${GETH_BOOTNODES}
      SEQUENCER_ADDRESS: ${SEQUENCER_ADDRESS}
      L2_CHAIN_ID: ${L2_CHAIN_ID}
    volumes:
      - opstack-volume:/opstack/
      - ./tools/templates:/opstack-temp/tools/templates
      - ./tools/bash_scripts:/opstack-temp/tools/bash_scripts
    depends_on:
      - builder
    restart:
      always
    ports:
      - ${DOCKER_HOST_IP:-127.0.0.1}:30303:30303
      - ${DOCKER_HOST_IP:-127.0.0.1}:8551:8551
      - ${DOCKER_HOST_IP:-127.0.0.1}:8545:8545
    command: "sh /opstack-temp/tools/bash_scripts/run_opgeth.sh"
  
  opnode:
    image: shards-builder
    container_name: 'opnode'
    environment:
      STATIC_NODES: ${STATIC_NODES}
      SEQ_KEY: ${PRIVATE_KEY_SEQUENCER}
      L1_RPC: ${L1_RPC}
      RPC_KIND: ${RPC_KIND}
    volumes:
      - opstack-volume:/opstack/
      - ./tools/templates:/opstack-temp/tools/templates
      - ./tools/bash_scripts:/opstack-temp/tools/bash_scripts
    depends_on:
      - builder
    restart: always
    ports:
      - ${DOCKER_HOST_IP:-127.0.0.1}:8547:8547
      - ${DOCKER_HOST_IP:-127.0.0.1}:9003:9003
    command: "sh /opstack-temp/tools/bash_scripts/run_opnode.sh"

  opbatcher:
    image: shards-builder
    container_name: 'opbatcher'
    environment:
      BATCHER_KEY: ${PRIVATE_KEY_BATCHER}
      L1_RPC: ${L1_RPC}
    volumes:
      - opstack-volume:/opstack/
      - ./tools/templates:/opstack-temp/tools/templates
      - ./tools/bash_scripts:/opstack-temp/tools/bash_scripts
    depends_on:
      - builder
    restart: always
    ports:
      - ${DOCKER_HOST_IP:-127.0.0.1}:8548:8548
    command: "sh /opstack-temp/tools/bash_scripts/run_opbatcher.sh"

  
  opproposer:
    image: shards-builder
    container_name: 'opproposer'
    environment:
      PROPOSER_KEY: ${PRIVATE_KEY_PROPOSER}
      L1_RPC: ${L1_RPC}
    volumes:
      - opstack-volume:/opstack/
      - ./tools/templates:/opstack-temp/tools/templates
      - ./tools/bash_scripts:/opstack-temp/tools/bash_scripts
    depends_on:
      - builder
    restart: always
    command: "sh /opstack-temp/tools/bash_scripts/run_opproposer.sh"


volumes:
  opstack-volume:

networks:
  shared_network:
